---
# handlers file for configure
- name: step-agent reload
  ansible.builtin.systemd_service:
    name: step-agent
    state: reloaded

- name: step-agent restart
  ansible.builtin.systemd_service:
    name: step-agent
    state: restarted

- name: step-agent reload-or-restart
  ansible.builtin.command: systemctl reload-or-restart step-agent.service
