---
# tasks file for configure

- name: Create Smallstep collection
  local_action:
        module: smallstep.agent.collection
        api_host: "{{ smallstep_api_host | default(omit) }}"
        api_token: "{{ smallstep_api_token }}"
        device_type: "{{ item.device_type }}"
        admin_emails: "{{ item.admin_emails }}"
        display_name: "{{ item.display_name }}"
        collection_slug: "{{ item.collection_slug }}"
        state: "{{ item.state | default('present') }}"
  loop:
    "{{ smallstep_collections }}"
  run_once: True
  become: False
  register: smallstep_collection_create

- name: Create Smallstep workload
  local_action:
        module: smallstep.agent.workload
        admin_emails: "{{ item.admin_emails }}"
        api_host: "{{ smallstep_api_host | default(omit) }}"
        api_token: "{{ smallstep_api_token }}"
        certificate_info: "{{ item.certificate_info | default(omit) }}"
        collection_slug: "{{ item.collection_slug }}"
        device_metadata_key_sans: "{{ item.device_metadata_key_sans | default(omit) }}"
        hooks: "{{ item.hooks | default(omit) }}"
        key_info: "{{ item.key_info | default(omit) }}"
        display_name: "{{ item.display_name }}"
        reload_info: "{{ item.reload_info | default(omit) }}"
        static_sans: "{{ item.static_sans | default(omit) }}"
        workload_slug: "{{ item.workload_slug }}"
        workload_type: "{{ item.workload_type }}"
        state: "{{ item.state | default('present') }}"
  loop:
    "{{ smallstep_workloads }}"
  run_once: True
  become: False
  register: smallstep_workload_create

- name: Create Smallstep collection instances
  local_action:
        module: smallstep.agent.instance
        api_host: "{{ smallstep_api_host | default(omit) }}"
        api_token: "{{ smallstep_api_token }}"
        instance_id: "{{ item.instance_id }}"
        collection_slug: "{{ item.collection_slug }}"
        instance_metadata: "{{ item.instance_metadata }}"
        state: "{{ item.state | default('present') }}"
  loop:
    "{{ smallstep_collection_instances }}"
  run_once: True
  become: False
  register: smallstep_collection_create_instance

- name: Set smallstep_base_domain fact
  set_fact:
    smallstep_base_domain: "{{  smallstep_api_host.split('.')[1:] | lower }}"
  when: smallstep_api_host
  run_once: True

- name: Set agent.yaml facts
  ansible.builtin.set_fact:
    smallstep_fingerprint: "{{ smallstep_collection_create.results[0].smallstep_collection.fingerprint }}"
    smallstep_team: "{{ smallstep_collection_create.results[0].smallstep_collection.team }}"
  run_once: True

- name: Create /etc/step-agent/agent.yaml
  ansible.builtin.template:
    src: agent.yaml.j2
    dest: /etc/step-agent/agent.yaml
    owner: step-agent
    group: step-agent
    mode: 0644
  notify: step-agent reload-or-restart

- name: Start step-agent.service and ensure it is enabled
  ansible.builtin.systemd:
    name: step-agent
    daemon_reload: true
    enabled: true
    state: started
