---
# tasks file for install
- name: Performing Tasks to detect OS arch and set step-agent version
  include_tasks: package.yml

- name: Performing step-agent install tasks for Red Hat based distributions
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Performing step-agent install tasks for Debian based distributions
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"
