name: Run Ansible Sanity Tests

on:
  push:
    tags-ignore:
    - 'v*'
    branches:
    - "main"
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/smallstep/agent

    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
        with:
          path: ansible_collections/smallstep/agent

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Ansible
        run: pip install ansible

      - name: Run the sanity tests
        run: ansible-test sanity --skip-test validate-modules
